### ISSUE TITLE
new server crash in latest version.

### ISSUE THREAD

**Issue by IronworksProductions** [WinDanesz/LostBooks-II#2]
I am getting this now in the latest update.
[crash-2020-06-08_03.43.10-server.txt](https://github.com/WinDanesz/LostBooks-II/files/4743752/crash-2020-06-08_03.43.10-server.txt)

**Comment by WinDanesz** [comment]
Looks like a Linux server specific error with the config file writer. 
I've tested it on windows where it had no issues. Will fix that, sorry about it.

**Comment by Sereath** [comment]
Here to report the same issue, this only happens when launching a server.
The desktop where I run it has Windows 10
[crash-2020-06-14_18.41.07-server.txt](https://github.com/WinDanesz/LostBooks-II/files/4777414/crash-2020-06-14_18.41.07-server.txt)

LostBooks-II-1.12.2-2.0.1

**Comment by WinDanesz** [comment]
Fixed, release is now on curseforge
25be66d
